apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calamp-listener
  namespace: redsky
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    # cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  # tls:
  #   - hosts:
  #     - redsky.do.cpht.io
  #     secretName: redsky.do.cpht.io
  rules:
  - host: redsky.do.cpht.io
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: calamp-listener
              port:
                number: 20500
                number: 20505
